FROM node:10.16.3-alpine AS builder
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5050
# ENV NODE_ENV=development
# ENV PORT=5000
# ENV DATABASE_PROVIDER=mongodb
# ENV DATABASE_HOST=localhost
# ENV DATABASE_PORT=27017
# ENV DATABASE_NAME=test
# ENV DATABASE_USER=blogadmin
CMD [ "npm", "start" ]